# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contigency_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(406, 376)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 101, 16))
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(30, 180, 110, 22))
        self.dateEdit.setDate(QtCore.QDate(2018, 4, 7))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(Form)
        self.dateEdit_2.setGeometry(QtCore.QRect(30, 240, 110, 22))
        self.dateEdit_2.setDate(QtCore.QDate(2018, 5, 29))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(230, 140, 95, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 160, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(230, 180, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(230, 120, 101, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 310, 241, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(220, 210, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(260, 240, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(260, 270, 101, 16))
        self.label_10.setObjectName("label_10")
        self.verticalSlider_2 = QtWidgets.QSlider(Form)
        self.verticalSlider_2.setGeometry(QtCore.QRect(220, 240, 22, 51))
        self.verticalSlider_2.setMaximum(1)
        self.verticalSlider_2.setProperty("value", 1)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(40, 20, 211, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 90, 311, 16))
        self.label_12.setObjectName("label_12")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(40, 50, 62, 22))
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.001)
        self.doubleSpinBox.setProperty("value", 0.001)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox1 = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox1.setGeometry(QtCore.QRect(40, 120, 61, 22))
        self.doubleSpinBox1.setMaximum(10.0)
        self.doubleSpinBox1.setSingleStep(0.1)
        self.doubleSpinBox1.setProperty("value", 0.01)
        self.doubleSpinBox1.setObjectName("doubleSpinBox1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Начальная дата"))
        self.label_3.setText(_translate("Form", "Конечная дата"))
        self.radioButton.setText(_translate("Form", "EUR/USD"))
        self.radioButton_2.setText(_translate("Form", "GBP/USD"))
        self.radioButton_3.setText(_translate("Form", "USD/JPY"))
        self.label_4.setText(_translate("Form", "Валютная пара"))
        self.pushButton.setText(_translate("Form", "Построить таблицу сопряженности"))
        self.label_8.setText(_translate("Form", "Тип корпуса"))
        self.label_9.setText(_translate("Form", "usd"))
        self.label_10.setText(_translate("Form", "native"))
        self.label_11.setText(_translate("Form", "Величина перепада курсов валют"))
        self.label_12.setText(_translate("Form", "Величина перепада эмоциональных оценок"))
