# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'histogram_drawer_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 459)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 101, 16))
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(30, 180, 110, 22))
        self.dateEdit.setDate(QtCore.QDate(2018, 4, 7))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(Form)
        self.dateEdit_2.setGeometry(QtCore.QRect(30, 240, 110, 22))
        self.dateEdit_2.setDate(QtCore.QDate(2018, 5, 29))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(40, 300, 95, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 320, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 340, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 280, 101, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 390, 161, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(190, 110, 161, 16))
        self.label_5.setObjectName("label_5")
        self.verticalSlider = QtWidgets.QSlider(Form)
        self.verticalSlider.setGeometry(QtCore.QRect(190, 140, 22, 51))
        self.verticalSlider.setMaximum(1)
        self.verticalSlider.setProperty("value", 1)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(230, 140, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(230, 170, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(190, 200, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(230, 230, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(230, 260, 101, 16))
        self.label_10.setObjectName("label_10")
        self.verticalSlider_2 = QtWidgets.QSlider(Form)
        self.verticalSlider_2.setGeometry(QtCore.QRect(190, 230, 22, 51))
        self.verticalSlider_2.setMaximum(1)
        self.verticalSlider_2.setProperty("value", 1)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(40, 20, 211, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 90, 311, 16))
        self.label_12.setObjectName("label_12")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(40, 50, 62, 22))
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.001)
        self.doubleSpinBox.setProperty("value", 0.001)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(40, 120, 61, 22))
        self.spinBox.setProperty("value", 3)
        self.spinBox.setObjectName("spinBox")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(230, 320, 101, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(190, 290, 161, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(230, 350, 101, 16))
        self.label_15.setObjectName("label_15")
        self.verticalSlider_3 = QtWidgets.QSlider(Form)
        self.verticalSlider_3.setGeometry(QtCore.QRect(190, 320, 22, 51))
        self.verticalSlider_3.setMaximum(1)
        self.verticalSlider_3.setProperty("value", 1)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Начальная дата"))
        self.label_3.setText(_translate("Form", "Конечная дата"))
        self.radioButton.setText(_translate("Form", "EUR/USD"))
        self.radioButton_2.setText(_translate("Form", "GBP/USD"))
        self.radioButton_3.setText(_translate("Form", "USD/JPY"))
        self.label_4.setText(_translate("Form", "Валютная пара"))
        self.pushButton.setText(_translate("Form", "Построить гистограмму"))
        self.label_5.setText(_translate("Form", "Тим эмоционалной оценки"))
        self.label_6.setText(_translate("Form", "Положительная"))
        self.label_7.setText(_translate("Form", "Отрицательная"))
        self.label_8.setText(_translate("Form", "Тип пика"))
        self.label_9.setText(_translate("Form", "Bear"))
        self.label_10.setText(_translate("Form", "Bull"))
        self.label_11.setText(_translate("Form", "Величина перепада курсов валют"))
        self.label_12.setText(_translate("Form", "Величина перепада эмоциональных оценок"))
        self.label_13.setText(_translate("Form", "usd"))
        self.label_14.setText(_translate("Form", "Тип словаря"))
        self.label_15.setText(_translate("Form", "native"))
